### ISSUE TITLE
Fix linking so go-mobile remains discoverable

### ISSUE THREAD

**Issue by andrewxhill** [textileio/react-native-sdk#1]
Currently after I link the file into textile-mobile, I need to go Xcode -> LIbraries -> RNTextile and change all the search paths for go-mobile to `$(SRCROOT)/../../go-mobile/ios`

Any time `react-native-sdk` is updated I need to repeat that step...

**Comment by asutula** [comment]
How are you updating `react-native-sdk`. If you just let `yarn` to the updating, it shouldn't touch your Xcode project configuration. I guess maybe you're running `react-native link` again? Is that necessary?

**Comment by andrewxhill** [comment]
This should be fixed in `1.0.16`

**Comment by andrewxhill** [comment]
The problem is just the search paths shipped in RNTextile need to be pre-set to be relive to a parent project where it is going to exist inside `node_modules/@textile/` and it just wants to go back into `@textile` to locate `go-mobile`.
