### ISSUE TITLE
Not clear how to decode the feed result

### ISSUE THREAD

**Issue by andrewxhill** [textileio/react-native-sdk#118]
when collecting results from `Textile.feed` it isn't clear how to get those results back into JS/TS types. I'm guessing it is something to do with the `result.payload.value` content, but I don't see any section in the docs about Feed so it's tricky still.

**Comment by asutula** [comment]
Yea it's a gross part of the API. You can look at the Photos app as an example, but I have a plan here:

The native sdks are going to decode the feed items a return a list of decoded objects. In Objective C and Swift and Java, this will likely implemented using a struct of an enum "type" and a property of each object type that will each be nil other than the one that corresponds to the "type" enum and is the current item:

```
{
    type: FeedItemType,
    files?: IFIles,
    message?: IText,
    ...
}
```
 
The TS extension to this will be similar, but use a nice type discriminated union to represent the different possibilities. 

The same decoding and structure will be used for the thread update events. Can knock this out ASAP if you need @andrewxhill .
