### ISSUE TITLE
Update iOS docs to indicate platform version minimum

### ISSUE THREAD

**Issue by jehunter5811** [textileio/react-native-sdk#158]
In the docs for ios, there is a podfile update that needs to happen. However, if you create a new react native project and the platform version is <10, pod install will fail. Docs should be updated to indicate that in addition to updating the pod line, the developer should check the top of the podfile for the platform version. 

Docs link: https://docs.textile.io/develop/clients/react-native/#ios-setup

**Comment by poocart** [comment]
Hey, having same issues while running `pod install` with Pods and Podfile.lock removed. So far I've tried:
- setting iOS platform target to 10.0 on both Podfile or project level
- setting iOS platform target to 10.0 on library podspec
- removing Textile pod version from library helped to install pods, but probably it fetched older version as the build process failed in progress

**Comment by asutula** [comment]
Sorry this fell behind. The latest version of the sdk seems to work fine on a freshly created react native project. The whole stack of libraries (Textile Core, Textile iOS, react-native-sdk) now just require a target iOS version of 9.0 or higher.
