### ISSUE TITLE
Add textile.initialize.seed method

### ISSUE THREAD

**Issue by andrewxhill** [textileio/react-native-sdk#88]
Ideally, this could work even if a repo already existed with a different seed, wiping it out. Perhaps by adding a force=true flag.

**Comment by asutula** [comment]
Did we have this previously in the react-native-sdk?

We've talked about this briefly on calls, but sounds like something that will take a little thinking about how to do file system management, what the ux of switching account should be etc.

**Comment by andrewxhill** [comment]
well... brute force and works is fine at first. we don't have to add it to the photos app, just need the api. i don't think it ever existed

**Comment by sanderpick** [comment]
The init config has a place for seed already:
```
// InitConfig is used to setup a textile node
type InitConfig struct {
	Seed      string
	RepoPath  string
	LogToDisk bool
	Debug     bool
}
```
would that do it?

**Comment by andrewxhill** [comment]
okay nice, the method exposed in this lib only takes the two `boolean` params. perhaps just supporting the seed param would do the trick!

**Comment by sanderpick** [comment]
Sweet. There are some old issues that will need to happen for the other part of this:

- https://github.com/textileio/go-textile/issues/468
- https://github.com/textileio/go-textile/issues/469

**Comment by asutula** [comment]
Is it up to the user of the sdk to manage different paths for different accounts? Or does that get managed internally by go-textile? Or do we just simply always pass in the same path and overwrite the repo that was previously there?

And, yea makes sense that we'll need the wallet api in place so we can query for all the possible accounts seeds/indexes etc to pass into the initialize api.
